apiVersion: v1
kind: Pod
metadata:
   name: linux-dev
spec:
   containers:
   - name: linux-dev
     image: localhost:5000/server/linux-dev:0.1
     command: [ "/bin/bash", "-c", "--" ]
     args: [ "while true; do sleep 30; done;" ]
